/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as EventSlugGalleryRouteImport } from './routes/event.$slug.gallery'
import { Route as AdminEventSlugRouteImport } from './routes/admin.event.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugGalleryRoute = EventSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EventSlugRoute,
} as any)
const AdminEventSlugRoute = AdminEventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/event/$slug': typeof EventSlugRouteWithChildren
  '/admin/event/$slug': typeof AdminEventSlugRoute
  '/event/$slug/gallery': typeof EventSlugGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/event/$slug': typeof EventSlugRouteWithChildren
  '/admin/event/$slug': typeof AdminEventSlugRoute
  '/event/$slug/gallery': typeof EventSlugGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/event/$slug': typeof EventSlugRouteWithChildren
  '/admin/event/$slug': typeof AdminEventSlugRoute
  '/event/$slug/gallery': typeof EventSlugGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/event/$slug'
    | '/admin/event/$slug'
    | '/event/$slug/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/event/$slug'
    | '/admin/event/$slug'
    | '/event/$slug/gallery'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/event/$slug'
    | '/admin/event/$slug'
    | '/event/$slug/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventSlugRoute: typeof EventSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug/gallery': {
      id: '/event/$slug/gallery'
      path: '/gallery'
      fullPath: '/event/$slug/gallery'
      preLoaderRoute: typeof EventSlugGalleryRouteImport
      parentRoute: typeof EventSlugRoute
    }
    '/admin/event/$slug': {
      id: '/admin/event/$slug'
      path: '/event/$slug'
      fullPath: '/admin/event/$slug'
      preLoaderRoute: typeof AdminEventSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventSlugRoute: typeof AdminEventSlugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventSlugRoute: AdminEventSlugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventSlugRouteChildren {
  EventSlugGalleryRoute: typeof EventSlugGalleryRoute
}

const EventSlugRouteChildren: EventSlugRouteChildren = {
  EventSlugGalleryRoute: EventSlugGalleryRoute,
}

const EventSlugRouteWithChildren = EventSlugRoute._addFileChildren(
  EventSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EventSlugRoute: EventSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
